config_version = 12

[bar.default]
end = [ "notifications", "clipboard", "network", "volume", "session" ]
font_family = "JetBrainsMono Nerd Font"
reserve_space = false
smart_auto_hide = true
start = [ "control-center", "launcher", "workspaces" ]

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1720.0
    cy = 1258.0
    output = "DP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
font_family = "JetBrainsMono Nerd Font"

    [shell.panel]
    launcher_placement = "attached"

[theme]
builtin = "Catppuccin"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "hyprland", "qt" ]

[wallpaper]
directory = "/home/apoptosis/.config/wallpaper"

[weather]
unit = "imperial"

[widget.clock]
format = "{:%Y-%m-%d %I:%M %p}"

[widget.control-center]
glyph = "home"

[widget.network]
show_label = false

[widget.volume]
show_label = false