backend = 'fastresize'
color_space = 'lch'
palette = 'dark'

[templates]
text = { template = 'text.j2',  target = '~/.config/wallust/testing/theme.txt' }
css = { template = 'css.j2', target = '~/.config/wallust/testing/theme.css' }
json = { template = 'json.j2', target = '~/.config/wallust/testing/theme.json' }
hypr = { template = 'hypr.j2', target = '~/.config/wallust/testing/hypr.conf' } 
hyprpaper = { template = 'hyprpaper.j2', target = '~/.config/wallust/testing/hyprpaper.conf' }
mako = { template = 'mako.j2', target = '~/.config/wallust/testing/mako.conf' } 
waybar = { template = 'waybar.j2', target = '~/.config/wallust/testing/waybar.css' } 
rofi = { template = 'rofi.j2', target = '~/.config/wallust/testing/rofi.rasi' } 
ghostty = { template = 'ghostty.j2', target = '~/.config/wallust/testing/ghostty.conf' } 
nvim = { template = 'nvim.j2', target = '~/.config/wallust/testing/nvim.vim' } 
btop = { template = 'btop.j2', target = '~/.config/wallust/testing/btop.conf' } 
gtk = { template = 'gtk.j2', target = '~/.config/wallust/testing/gtk.css' } 
vscode = { template = 'vscode.j2', target = '~/.config/wallust/testing/vscode.txt' } 
vscode_json = { template = 'vscode_json.j2', target = '~/.config/wallust/testing/vscode.json' }