backend = 'fastresize'
color_space = 'lch'
palette = 'dark'

[templates]
hypr = { template = 'hypr.j2', target = '~/.config/hypr/theme.conf' } 
hyprpaper = { template = 'hyprpaper.j2', target = '~/.config/hypr/hyprpaper.conf' }
mako = { template = 'mako.j2', target = '~/.config/mako/config' } 
waybar = { template = 'waybar.j2', target = '~/.config/waybar/theme.css' } 
rofi = { template = 'rofi.j2', target = '~/.config/rofi/themes/theme.rasi' } 
ghostty = { template = 'ghostty.j2', target = '~/.config/ghostty/theme.conf' } 
nvim = { template = 'nvim.j2', target = '~/.config/nvim/theme.vim' } 
btop = { template = 'btop.j2', target = '~/.config/btop/themes/current.theme' }